name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y g++ libgtest-dev

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake ../src

    - name: Build
      run: |
        cd build
        make

    - name: Run tests
      run: |
        cd build
        ./frequency_dictionary_test
